MrcCoreMvc/Controllers/MemberController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MRCDataLibrary._02_Models;
using MRCDataLibrary._03_Data;

namespace MrcCoreMvc.Controllers
{
    [Authorize(Roles = "Manager")]
    public class MemberController : Controller
    {
        private readonly IMemberData _memberData;
        private readonly ICodeMasterData _codeMasterData;

        public MemberController(IMemberData memberData, ICodeMasterData codeMasterData)
        {
            _memberData = memberData;
            _codeMasterData = codeMasterData;
        }

        public async Task<IActionResult> Index()
        {
            var members = await _memberData.GetMembers();
            var groupType = await _codeMasterData.GetCodeList("GROUP_CD");
            var teamType = await _codeMasterData.GetCodeList("TEAM_CD");
            members.ForEach(x =>
            {
                x.GroupName = groupType.Where(g => x.GroupCd == g.CODE_ID).FirstOrDefault()?.CODE_DESCR;
                x.TeamName = teamType.Where(t => x.TeamCd == t.CODE_ID).FirstOrDefault()?.CODE_DESCR;
            });
            return View(members);
        }

        public async Task<IActionResult> Create()
        {
            var member = new MemberModel();
            var groupType = await _codeMasterData.GetCodeList("GROUP_CD");
            groupType.ForEach(x =>
            {
                member.GroupSelectList.Add(new SelectListItem { Value = x.CODE_ID, Text = x.CODE_DESCR });
            });
            var teamType = await _codeMasterData.GetCodeList("TEAM_CD");
            teamType.ForEach(x =>
            {
                member.TeamSelectList.Add(new SelectListItem { Value = x.CODE_ID, Text = x.CODE_DESCR });
            });
            return View(member);
        }

        [HttpPost]
        public async Task<IActionResult> Create(MemberModel member)
        {
            if(ModelState.IsValid == false)
            {
                return View();
            }

            string id = await _memberData.CreateMember(member);
            return RedirectToAction("Detail", new { memberId = id });
        }

        public async Task<IActionResult> Detail(string memberId)
        {
            var member = await _memberData.GetMemberById(memberId);
            var groupType = await _codeMasterData.GetCodeList("GROUP_CD");
            groupType.ForEach(x =>
            {
                member.GroupSelectList.Add(new SelectListItem { Value = x.CODE_ID, Text = x.CODE_DESCR });
            });
            var teamType = await _codeMasterData.GetCodeList("TEAM_CD");            
            teamType.ForEach(x =>
            {
                member.TeamSelectList.Add(new SelectListItem { Value = x.CODE_ID, Text = x.CODE_DESCR });
            });

            return View(member);
        }

        [HttpPost]
        public async Task<IActionResult> Update(MemberModel member)
        {
            string memberId = await _memberData.UpdateMember(member);
            return RedirectToAction("Detail", new { memberId });
        }

        public async Task<IActionResult> Delete(string memberId)
        {
            var member = await _memberData.GetMemberById(memberId);
            return View(member);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(MemberModel member)
        {
            await _memberData.DeleteMember(member.MemberId);
            return RedirectToAction("Index");
        }
    }
}

MrcCoreMvc/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.V3.Pages.Account.Manage.Internal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MrcCoreMvc.Areas.Identity.Data;
using MRCDataLibrary._02_Models;
using MRCDataLibrary._03_Data;

namespace MrcCoreMvc.Controllers
{
    [Authorize(Roles = "Manager,Administrator")]
    public class UserController : Controller
    {
        private readonly IUserData _userData;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<DeletePersonalDataModel> _logger;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(IUserData userData,
                              UserManager<ApplicationUser> userManager,
                              ILogger<DeletePersonalDataModel> logger,
                              RoleManager<IdentityRole> roleManager)
        {
            _userData = userData;
            _userManager = userManager;
            _logger = logger;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
            var userInfo = await _userManager.GetUserAsync(User);
            return View(userInfo);
        }

        [HttpGet]
        public async Task<IActionResult> GetUsers()
        {
            var users = await _userData.GetUsers();
            return Json(new { data = users.ToList() });
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            var user = await _userData.GetUser(id);
            var roles = _roleManager.Roles;
            await roles.ForEachAsync(x =>
             {
                 user.RoleSelectList.Add(new SelectListItem { Value = x.Id, Text = x.Name });
                 user.Roles.Add(x.Name);
             });

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(UserModel user, List<string> Roles)
        {
            string id = await _userData.UpdateUser(user);
            string role = String.Join(",", Roles.ToArray());
            return RedirectToAction("Details", new { id });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(string id)
        {
            //var user = await _userData.GetUser(id);
            var result = await _userData.DeleteUser(id);
            if (result <= 0)
            {
                throw new InvalidOperationException($"Unexpected error occurred deleting user with ID '{id}'.");
            }

            _logger.LogInformation("User with ID '{UserId}' deleted themselves.", id);

            //return Redirect("~/");
            return Json(new { success = true, message = "Delete successful" });
        }
    }
}

MrcCoreMvc/Controllers/UserRoleController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MRCDataLibrary._03_Data;

namespace MrcCoreMvc.Controllers
{
    [Authorize(Roles = "Manager")]
    public class UserRoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IUserData _userData;

        public UserRoleController(RoleManager<IdentityRole> roleManager, IUserData userData)
        {
            _roleManager = roleManager;
            _userData = userData;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetRoles()
        {
            var roles = _roleManager.Roles;
            return Json(new { data = roles.ToList() });
        }

        [HttpGet]
        public async Task<IActionResult> Details(string name)
        {
            var role = await _roleManager.FindByNameAsync(name);
            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(IdentityRole role)
        {
            var thisRole = await _roleManager.FindByIdAsync(role.Id);
            thisRole.Name = role.Name;
            var result = await _roleManager.UpdateAsync(thisRole);

            if (result.Succeeded)
            {
                return RedirectToAction("Details", new { name = role.Name });
            }
            else
            {
                return View();
            }
        }

        public IActionResult Create()
        {
            var newRole = new IdentityRole();
            return View(newRole);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            var result = await _roleManager.CreateAsync(new IdentityRole(role.Name));
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            var result = await _roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                return Json(new { success = true, message = "Delete successful" });
            }
            else
            {
                return View();
            }
        }
    }
}

MrcCoreMvc/Controllers/WorshipController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MRCDataLibrary._02_Models;
using MRCDataLibrary._03_Data;

namespace MrcCoreMvc.Controllers
{
    public class WorshipController : Controller
    {
        private readonly IWorshipData _worshipData;
        private readonly ICodeMasterData _codeMasterData;

        public WorshipController(IWorshipData worshipData, ICodeMasterData codeMasterData)
        {
            _worshipData = worshipData;
            _codeMasterData = codeMasterData;
        }

        public IActionResult Index()
        {
            return View();
        }
        // GET: WorshipController
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var worships = await _worshipData.GetWorships();
            var worshipType = await _codeMasterData.GetCodeList("WORSHIP_TYPE");
            worships.ForEach(x =>
            {
                x.WorshipName = worshipType.Where(n => x.WorshipType == n.CODE_ID).FirstOrDefault()?.CODE_DESCR;
                x.SimpleDate = x.WorshipDate.ToString("yyyy-MM-dd");
                x.SimpleTime = x.WorshipDate.ToString("HH:mm");
            });
            //return View(worships);
            return Json(new { data = worships.ToList() });
        }

        // GET: WorshipController/Details/5
        public async Task<IActionResult> Details(string worshipId)
        {
            var worship = new WorshipModel();
            worship = await _worshipData.GetWorshipById(worshipId);
            var worshipType = await _codeMasterData.GetCodeList("WORSHIP_TYPE");
            worshipType.ForEach(x =>
            {
                worship.WorshipTypeSelectList.Add(new SelectListItem { Value = x.CODE_ID, Text = x.CODE_DESCR });
            });
            return View(worship);
        }

        // GET: WorshipController/Create
        public async Task<IActionResult> Create()
        {
            var worship = new WorshipModel();
            var worshipType = await _codeMasterData.GetCodeList("WORSHIP_TYPE");
            worshipType.ForEach(x =>
            {
                worship.WorshipTypeSelectList.Add(new SelectListItem { Value = x.CODE_ID, Text = x.CODE_DESCR });
            });
            return View(worship);
        }

        // POST: WorshipController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(WorshipModel worship)
        {
            if(ModelState.IsValid == false)
            {
                return View();
            }
            string id = await _worshipData.CreateWorship(worship);
            return RedirectToAction("Details", new { worshipId = id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(WorshipModel worship)
        {
            string worshipId = await _worshipData.UpdateWorship(worship);
            return RedirectToAction("Details", new { worshipId });
        }


        //public async Task<IActionResult> Delete(string worshipId)
        //{
        //    var worship = await _worshipData.GetWorshipById(worshipId);
        //    return View(worship);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Delete(WorshipModel worship)
        //{
        //    await _worshipData.DeleteWorship(worship.WorshipId);
        //    return RedirectToAction("Index");
        //}

        [HttpDelete]
        public async Task<IActionResult> Delete(string worshipId)
        {
            await _worshipData.DeleteWorship(worshipId);
            //return RedirectToAction("Index");
            return Json(new { success = true, message = "Delete successful" });
        }
    }
}

MrcCoreMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MrcCoreMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @*Added//////////////////////////////////////////*@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css" />

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" >
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" >
    @*//////////////////////////////////////////////*@

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Ramwon Church</a>
                @*<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>*@
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    <partial name="_LoginPartial" /> @*Added*@

                <ul class="navbar-nav flex-grow-1">
                    @*<li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>*@

                    @if (User.IsInRole("Manager") || User.IsInRole("Administrator"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropDown" data-toggle="dropdown">
                                Admin
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item text-black-50" asp-controller="User" asp-action="Index">User Info</a>
                                <a class="dropdown-item text-black-50" asp-controller="UserRole" asp-action="Index">User Role</a>
                                @*<a class="dropdown-item text-black-50" asp-controller="Member" asp-action="Index">Member Info</a>*@
                                <a class="dropdown-item text-black-50" asp-controller="CodeMaster" asp-action="Index">Code Master</a>
                                <a class="dropdown-item text-black-50" asp-controller="CategoryMaster" asp-action="Index">Category Master</a>
                            </div>
                        </li>
                    }

                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Worship" asp-action="Index">Worship Info</a>
                    </li>

                </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white-50 bg-primary">
        <div class="container">
            &copy; 2020 - MrcCoreMvc - <a class="text-white-50" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    @*Added//////////////////////////////////////////*@
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cleave.js/1.4.10/cleave.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cleave.js/1.4.10/addons/cleave-phone.us.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=g28lhnxtlihu4l4a381gw7tz47voznshwbi10lmsvlekrfme"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.js"></script>
    @*//////////////////////////////////////////////*@


    @RenderSection("Scripts", required: false)
</body>
</html>